function Sound = gaglab_snd_init

Sound.UseSound = 0;
Sound.Stereo = 0;
Sound.FrequencyHz = 44100;
Sound.Nbits = 8;

Sound.Stimulus = struct(...
	'Handle', {}, ...
	'Stereo', {}, ...
	'Duration', {}, ...
	'FrequencyHz', {}, ...
	'Volume', {}, ...
	'Nbits', {}, ...
	'Loop', {}, ...
	'Data', {} ...
);

Sound.File = struct(...
	'Name', {}, ...
	'Stereo', {}, ...
	'Duration', {}, ...
	'FrequencyHz', {}, ...
	'Nbits', {}, ...
	'Data', {} ...
);

%Sound = gaglab_snd_preloadsounds(Sound, 0);